blank_issues_enabled: false
contact_links:
  - name: DynCore Discord Server
    url: https://discord.gg/DynCore
    about: Ask questions, receive support, and discuss with the community in our Discord server.
